name = "iota-wallet-website"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "50b1d8927fd141c8a286926deb5d5694"

[[d1_databases]]
binding = "DB"
database_name = "feedback_db"
database_id = "6b0e79e2-20e4-49e1-9ff0-2f266f19cda6"
